### ISSUE TITLE
MailChimp signups blocked as advertising

### ISSUE THREAD

**Issue by wesinator** [disconnectme/disconnect-tracking-protection#65] opened 2018-12-02 20:20 UTC
https://github.com/disconnectme/disconnect/issues/337

> A disconnect.me user reported that submit form on [www.virtkick.io](http://www.virtkick.io) doesn't work for him. I tried disconnect.me and I reproduced the problem. Why are you blocking legitimate JSONP requests to MailChimp?
> 
> ```
> Resource interpreted as Script but transferred with MIME type text/html: "about:blank".
> mailchimp ajax submit error: parsererror 
> ```

I can confirm this is an issue, MailChimp email signups are blocked under Advertising, causing signups to fail silently on many sites.

https://github.com/disconnectme/disconnect-tracking-protection/blob/efbfeabbdb3059956a89ae13a568e75f6bb6ecc2/services.json#L3879

**Comment by disconnectus** [comment] 2019-01-30 22:07
Hmm we can't reproduce this error on several websites that integrate MailChimp. Closing.

**Closed by disconnectus** 2019-01-30 22:07 UTC

**Comment by wesinator** [comment] 2019-02-07 01:17
@disconnectus 
https://quad9.net/news/

MailChimp signup at bottom of page, Subscribe button is blocked. Unchecking the MailChimp rule under advertising fixes the signup.

There is at least one more example of this I've come across, but I can't find it now.
Sorry for not including examples earlier

Thanks,
